import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Email Workflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              const theme = localStorage.getItem("theme");
              if (theme) {
                document.documentElement.dataset.theme = theme;
              }
            `,
          }}
        />

      </head>
      <body
        // data-theme="dark"
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        {children}
        <Toaster
          position="bottom-left"
          richColors
          theme="dark"
        />
      </body>
    </html>
  );
}
